
package ElementosAdministracion;


import Clases.Proyecto;
import Clases.Entregables;
import AdminAplication.MetodosPrincipales;
import AdminAplication.ProcesosMongoDB;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ElementosAdministracion.frmEquipoTrabajo;

public class AltaSolicitudProyecto extends javax.swing.JPanel {
    //Creacion de Clases necesarias
    private MetodosPrincipales Procedimiento = new MetodosPrincipales();//Clase para los procedimientos generales
    private ProcesosMongoDB ProcedimientoMongo = new ProcesosMongoDB();//Clase Para Procedimientos con la base de datos
    public Entregables Entregables;// Clase  de entregables de la tabla
    
    private String coleccionProyecto;
    private String coleccionEntregables;
    public ArrayList<String> Actividades;    
    
    private int SumaImporte;//Variable local para calcular el importe estimado y mostrarlo
    private String codificacion;
    //Crear Arreglos por cada Elemento de los entregables, Implementar una  Matriz No es eficiente :/
    ArrayList<String> descripcion;
    ArrayList<String> concepto;
    ArrayList<Integer> importe;
       
    public AltaSolicitudProyecto() {
        initComponents();
        //Inicializar las variables
        this.coleccionProyecto = "Proyectos";//Coleccion de Proyectos Para base de datos
        this.coleccionEntregables = "Entregables";//Coleccion de entregables Para base de datos
        this.Entregables = new Entregables();
        this.descripcion = new ArrayList<>();
        this.concepto = new ArrayList<>();
        this.importe = new ArrayList<>();
        this.Actividades = new ArrayList<>();
        this.SumaImporte = 0;
        this.codificacion = Procedimiento.GenerarCodificacion("Solicitud");
        this.txtFolio.setEditable(false);
        this.txtFolio.setText(codificacion);       
        
    }
    private void LimpiarForm(){
        tblDatosProyecto.setModel(new DefaultTableModel());
        txtCorreoAdminProyecto.setText("");
        txtCorreoTecnicoProyecto.setText("");
        txtNombreAdminProyecto.setText("");
        txtNombreTecnicoProyecto.setText("");
        txtTelefonoAdminPojecto.setText("");
        txtTelefonoTecniproyecto.setText("");
        
        txtConcepto.setText("");
        txtDescripcionEntregable.setText("");
        txtDescripcionProyecto.setText("");
        txtImporte.setText("");
        txtJustificacionProyecto.setText("");
        txtObjetivoProyecto.setText("");
        txtTituloProyecto.setText("");
        txtFolio.setText("");
        
        txtTituloProyecto.requestFocus();
    }
    public Proyecto LlenarDatosProyecto(){
        String Status="Pendiente";
        //Crear una clase de Tipo Proyecto
        Proyecto proyecto = new Proyecto();                   
        //Llenar la clase poyecto con los datos proporcionados
        proyecto.setCodigoProyecto(this.codificacion);
        proyecto.setNombreAdminProyecto(txtNombreAdminProyecto.getText());
        proyecto.setCorreoAdminProyecto(txtCorreoAdminProyecto.getText());
        proyecto.setTelefonoAdminProyecto(txtTelefonoAdminPojecto.getText());
        proyecto.setNombreTecnicoProyecto(txtNombreTecnicoProyecto.getText());
        proyecto.setCorreoTecnicoProyecto(txtCorreoTecnicoProyecto.getText());
        proyecto.setTelefonoTecnicoProyecto(txtTelefonoTecniproyecto.getText());
        proyecto.setTituloProyecto(txtTituloProyecto.getText());
        proyecto.setDescripcionProyecto(txtDescripcionProyecto.getText());
        proyecto.setObjetivosProyecto(txtObjetivoProyecto.getText());
        proyecto.setJustificacionProyecto(txtJustificacionProyecto.getText());
        proyecto.setActividades(Actividades);
        proyecto.setImporteEstimado(this.SumaImporte);
        proyecto.setStatusProyecto(Status);
         
        this.Entregables.setCodigo(codificacion);
        this.Entregables.setConcepto(this.concepto);
        this.Entregables.setDescripcion(this.descripcion);
        this.Entregables.setImporte(this.importe);    
        
        return proyecto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrSolicitud = new javax.swing.JScrollPane();
        pnlSolicitudProyecto = new javax.swing.JPanel();
        lblSolicitudproyecto = new javax.swing.JLabel();
        lblTituloProyecto = new javax.swing.JLabel();
        lblDescripcionProyecto = new javax.swing.JLabel();
        lblObjetivoProyecto = new javax.swing.JLabel();
        lblJustificacionProyecto = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JToggleButton();
        btnGuardarProyecto = new javax.swing.JToggleButton();
        lblDescripcionActividades = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtTituloProyecto = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtDescripcionProyecto = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        txtObjetivoProyecto = new javax.swing.JTextArea();
        jScrollPane21 = new javax.swing.JScrollPane();
        txtJustificacionProyecto = new javax.swing.JTextArea();
        lblResultadosEsperados = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        txtResultadosEsperados = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtActividad = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblActividades = new javax.swing.JTable();
        jlblActivdad = new javax.swing.JLabel();
        btnAgregarActividad = new javax.swing.JToggleButton();
        btnEliminarActividad = new javax.swing.JToggleButton();
        jbtnAgregarGrupoTrabajo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblConcepto = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtConcepto = new javax.swing.JTextPane();
        lblImporte = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtImporte = new javax.swing.JTextPane();
        btnAgregarEntregable = new javax.swing.JToggleButton();
        btnQuitarEntregable = new javax.swing.JToggleButton();
        jScrollPane16 = new javax.swing.JScrollPane();
        txtDescripcionEntregable = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblDatosProyecto = new javax.swing.JTable();
        lbldescripcion = new javax.swing.JLabel();
        lblImporteEstimado = new javax.swing.JLabel();
        lblSumaImporte = new javax.swing.JLabel();
        jlblEspecificacionEntregables = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlblAdminProyecto = new javax.swing.JLabel();
        txtNombreAdminProyecto = new javax.swing.JTextField();
        lblCorreoAdminProyecto = new javax.swing.JLabel();
        txtCorreoAdminProyecto = new javax.swing.JTextField();
        lblTecnicoProyecto = new javax.swing.JLabel();
        txtNombreTecnicoProyecto = new javax.swing.JTextField();
        lblCorreoTecnicoProyecto = new javax.swing.JLabel();
        txtCorreoTecnicoProyecto = new javax.swing.JTextField();
        lblTelefonoTecnicoProyecto = new javax.swing.JLabel();
        txtTelefonoTecniproyecto = new javax.swing.JTextField();
        lblTelefonAdminProyecto = new javax.swing.JLabel();
        txtTelefonoAdminPojecto = new javax.swing.JTextField();
        jlblAdminProyecto1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1220, 570));

        scrSolicitud.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrSolicitud.setPreferredSize(new java.awt.Dimension(1210, 565));

        pnlSolicitudProyecto.setAutoscrolls(true);
        pnlSolicitudProyecto.setPreferredSize(new java.awt.Dimension(1220, 2000));

        lblSolicitudproyecto.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblSolicitudproyecto.setText("Solicitud de Proyecto");

        lblTituloProyecto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTituloProyecto.setText("Título del proyecto");

        lblDescripcionProyecto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDescripcionProyecto.setText("Breve descripción de la propuesta");

        lblObjetivoProyecto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblObjetivoProyecto.setText("Objetivo del Proyecto");

        lblJustificacionProyecto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJustificacionProyecto.setText("Justificación");

        btnCancelar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardarProyecto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnGuardarProyecto.setText("Guardar");
        btnGuardarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProyectoActionPerformed(evt);
            }
        });

        lblDescripcionActividades.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDescripcionActividades.setText("Actividades a desarrollar");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("FOLIO:");

        txtFolio.setBackground(new java.awt.Color(204, 204, 204));
        txtFolio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtFolio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtTituloProyecto.setColumns(20);
        txtTituloProyecto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTituloProyecto.setLineWrap(true);
        txtTituloProyecto.setRows(5);
        jScrollPane9.setViewportView(txtTituloProyecto);

        txtDescripcionProyecto.setColumns(20);
        txtDescripcionProyecto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDescripcionProyecto.setLineWrap(true);
        txtDescripcionProyecto.setRows(5);
        txtDescripcionProyecto.setPreferredSize(new java.awt.Dimension(224, 80));
        jScrollPane13.setViewportView(txtDescripcionProyecto);

        txtObjetivoProyecto.setColumns(20);
        txtObjetivoProyecto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtObjetivoProyecto.setLineWrap(true);
        txtObjetivoProyecto.setRows(5);
        txtObjetivoProyecto.setPreferredSize(new java.awt.Dimension(224, 80));
        jScrollPane14.setViewportView(txtObjetivoProyecto);

        txtJustificacionProyecto.setColumns(20);
        txtJustificacionProyecto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtJustificacionProyecto.setLineWrap(true);
        txtJustificacionProyecto.setRows(5);
        txtJustificacionProyecto.setPreferredSize(new java.awt.Dimension(224, 80));
        jScrollPane21.setViewportView(txtJustificacionProyecto);

        lblResultadosEsperados.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblResultadosEsperados.setText("Resultados esperados");

        txtResultadosEsperados.setColumns(20);
        txtResultadosEsperados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtResultadosEsperados.setLineWrap(true);
        txtResultadosEsperados.setRows(5);
        txtResultadosEsperados.setPreferredSize(new java.awt.Dimension(224, 80));
        jScrollPane22.setViewportView(txtResultadosEsperados);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1013, 297));

        txtActividad.setColumns(20);
        txtActividad.setRows(5);
        jScrollPane2.setViewportView(txtActividad);

        tblActividades.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Actividad", "Actividad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblActividades.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblActividades.setColumnSelectionAllowed(true);
        jScrollPane5.setViewportView(tblActividades);
        tblActividades.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (tblActividades.getColumnModel().getColumnCount() > 0) {
            tblActividades.getColumnModel().getColumn(0).setPreferredWidth(150);
            tblActividades.getColumnModel().getColumn(1).setPreferredWidth(900);
        }

        jlblActivdad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblActivdad.setText("Actividad:");

        btnAgregarActividad.setBackground(new java.awt.Color(123, 211, 123));
        btnAgregarActividad.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnAgregarActividad.setForeground(new java.awt.Color(59, 144, 59));
        btnAgregarActividad.setSelected(true);
        btnAgregarActividad.setText("+");
        btnAgregarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActividadActionPerformed(evt);
            }
        });

        btnEliminarActividad.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarActividad.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnEliminarActividad.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarActividad.setSelected(true);
        btnEliminarActividad.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblActivdad))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregarActividad)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblActivdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminarActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregarActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbtnAgregarGrupoTrabajo.setBackground(new java.awt.Color(0, 204, 255));
        jbtnAgregarGrupoTrabajo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbtnAgregarGrupoTrabajo.setText("Agregar Grupo de Trabajo");
        jbtnAgregarGrupoTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarGrupoTrabajoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setEnabled(false);

        lblConcepto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblConcepto.setText("Concepto");

        txtConcepto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(txtConcepto);

        lblImporte.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblImporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImporte.setText("Importe (Moneda nacional)");

        txtImporte.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jScrollPane7.setViewportView(txtImporte);

        btnAgregarEntregable.setBackground(new java.awt.Color(123, 211, 123));
        btnAgregarEntregable.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnAgregarEntregable.setForeground(new java.awt.Color(59, 144, 59));
        btnAgregarEntregable.setSelected(true);
        btnAgregarEntregable.setText("+");
        btnAgregarEntregable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEntregableActionPerformed(evt);
            }
        });

        btnQuitarEntregable.setBackground(new java.awt.Color(255, 51, 51));
        btnQuitarEntregable.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnQuitarEntregable.setForeground(new java.awt.Color(255, 255, 255));
        btnQuitarEntregable.setSelected(true);
        btnQuitarEntregable.setText("-");

        txtDescripcionEntregable.setColumns(20);
        txtDescripcionEntregable.setRows(5);
        txtDescripcionEntregable.setPreferredSize(new java.awt.Dimension(1050, 94));
        jScrollPane16.setViewportView(txtDescripcionEntregable);

        tblDatosProyecto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblDatosProyecto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblDatosProyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Orden de Trabajo", "Concepto", "Descripción", "Importe4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDatosProyecto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblDatosProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        tblDatosProyecto.setFillsViewportHeight(true);
        tblDatosProyecto.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tblDatosProyecto.setPreferredSize(new java.awt.Dimension(1040, 0));
        tblDatosProyecto.setRowHeight(50);
        tblDatosProyecto.getTableHeader().setResizingAllowed(false);
        tblDatosProyecto.getTableHeader().setReorderingAllowed(false);
        tblDatosProyecto.setUpdateSelectionOnSort(false);
        jScrollPane8.setViewportView(tblDatosProyecto);
        if (tblDatosProyecto.getColumnModel().getColumnCount() > 0) {
            tblDatosProyecto.getColumnModel().getColumn(0).setResizable(false);
            tblDatosProyecto.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblDatosProyecto.getColumnModel().getColumn(1).setPreferredWidth(300);
            tblDatosProyecto.getColumnModel().getColumn(2).setPreferredWidth(550);
            tblDatosProyecto.getColumnModel().getColumn(3).setResizable(false);
            tblDatosProyecto.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        lbldescripcion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbldescripcion.setText("Descripción");

        lblImporteEstimado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblImporteEstimado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblImporteEstimado.setText("Suma de importe total estimado:");

        lblSumaImporte.setBackground(new java.awt.Color(255, 255, 255));
        lblSumaImporte.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblSumaImporte.setText("$$");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbldescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(327, 327, 327)
                                .addComponent(lblImporte))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(238, 238, 238)
                                        .addComponent(btnAgregarEntregable, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnQuitarEntregable, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lblImporteEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(34, 34, 34)
                                            .addComponent(lblSumaImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane16)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConcepto)
                    .addComponent(lblImporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jScrollPane7))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregarEntregable)
                        .addComponent(btnQuitarEntregable)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbldescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImporteEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSumaImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jlblEspecificacionEntregables.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblEspecificacionEntregables.setText("Especificacion de Entregables");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlblAdminProyecto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblAdminProyecto.setText("Responsable Administrativo del Proyecto");

        txtNombreAdminProyecto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblCorreoAdminProyecto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCorreoAdminProyecto.setText("Correo");

        txtCorreoAdminProyecto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblTecnicoProyecto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTecnicoProyecto.setText("Responsable Técnico del Proyecto");

        txtNombreTecnicoProyecto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblCorreoTecnicoProyecto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCorreoTecnicoProyecto.setText("Correo");

        txtCorreoTecnicoProyecto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblTelefonoTecnicoProyecto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTelefonoTecnicoProyecto.setText("Télefono");

        txtTelefonoTecniproyecto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblTelefonAdminProyecto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTelefonAdminProyecto.setText("Télefono");

        txtTelefonoAdminPojecto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCorreoAdminProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreAdminProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreTecnicoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreoTecnicoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblCorreoAdminProyecto)
                    .addComponent(lblCorreoTecnicoProyecto)
                    .addComponent(lblTecnicoProyecto)
                    .addComponent(jlblAdminProyecto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefonoAdminPojecto, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonAdminProyecto)
                    .addComponent(lblTelefonoTecnicoProyecto)
                    .addComponent(txtTelefonoTecniproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlblAdminProyecto)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreAdminProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCorreoAdminProyecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreoAdminProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTecnicoProyecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreTecnicoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTelefonAdminProyecto)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefonoAdminPojecto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(lblTelefonoTecnicoProyecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefonoTecniproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCorreoTecnicoProyecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreoTecnicoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jlblAdminProyecto1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblAdminProyecto1.setText("Información de Responsables");

        javax.swing.GroupLayout pnlSolicitudProyectoLayout = new javax.swing.GroupLayout(pnlSolicitudProyecto);
        pnlSolicitudProyecto.setLayout(pnlSolicitudProyectoLayout);
        pnlSolicitudProyectoLayout.setHorizontalGroup(
            pnlSolicitudProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSolicitudProyectoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlSolicitudProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSolicitudProyectoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSolicitudproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSolicitudProyectoLayout.createSequentialGroup()
                        .addGroup(pnlSolicitudProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane22, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSolicitudProyectoLayout.createSequentialGroup()
                                .addComponent(jbtnAgregarGrupoTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(408, 408, 408)
                                .addComponent(btnGuardarProyecto)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1143, Short.MAX_VALUE))
                        .addGap(49, 49, 49))))
            .addGroup(pnlSolicitudProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSolicitudProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSolicitudProyectoLayout.createSequentialGroup()
                        .addGroup(pnlSolicitudProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcionProyecto)
                            .addComponent(lblTituloProyecto))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSolicitudProyectoLayout.createSequentialGroup()
                        .addGroup(pnlSolicitudProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlSolicitudProyectoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane13))
                            .addGroup(pnlSolicitudProyectoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlSolicitudProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 1142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 1141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 1141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(49, 49, 49))))
            .addGroup(pnlSolicitudProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSolicitudProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblEspecificacionEntregables)
                    .addComponent(jlblAdminProyecto1)
                    .addComponent(lblResultadosEsperados)
                    .addComponent(lblDescripcionActividades)
                    .addComponent(lblObjetivoProyecto)
                    .addComponent(lblJustificacionProyecto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSolicitudProyectoLayout.setVerticalGroup(
            pnlSolicitudProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSolicitudProyectoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnlSolicitudProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSolicitudproyecto)
                    .addGroup(pnlSolicitudProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jlblAdminProyecto1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTituloProyecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDescripcionProyecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblObjetivoProyecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblJustificacionProyecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblResultadosEsperados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblDescripcionActividades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlblEspecificacionEntregables)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlSolicitudProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAgregarGrupoTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarProyecto)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        scrSolicitud.setViewportView(pnlSolicitudProyecto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProyectoActionPerformed
        // TODO add your handling code here:
        Proyecto _proyecto = LlenarDatosProyecto();
        //Invocar el Método para guardar la Información
        String Resultado = ProcedimientoMongo.GuardarProyecto(this.coleccionProyecto, _proyecto, this.coleccionEntregables, this.Entregables );
      //  String Resultado2 = ProcedimientoMongo.GuardarEntregables(this.coleccion2, entregables);
       if (Resultado.equals("Guardado"))
            JOptionPane.showMessageDialog(this, "Los datos fueron Guardados con Éxito");
        this.LimpiarForm();
    }//GEN-LAST:event_btnGuardarProyectoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.LimpiarForm();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarEntregableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEntregableActionPerformed
        // TODO add your handling code here:
        int fila = this.tblDatosProyecto.getRowCount();//Cuenta los renglones usados de la tabla
        String OT = "OT";//Cadena para formar la orden de trabajo 
        //Obtener la informacion proporcionada desde el formulario    
        String  Concepto = this.txtConcepto.getText(),
                Descripcion = this.txtDescripcionEntregable.getText(),
                Importe =  this.txtImporte.getText(); 
        //Verificar que ningun campo esté vacío
        if(Concepto.isEmpty() || Descripcion.isEmpty() || Importe.isEmpty()){
            JOptionPane.showMessageDialog(this, "No se puede agregar la ctividad, hay algunos campos vacios");
            return;        
        }
        else if (Importe.matches("[0-9]*")){ // si el importe es un numero, Sumar y Mostrar el importe estimado                    
            this.SumaImporte+=Integer.parseInt(Importe);
            this.lblSumaImporte.setText(String.valueOf(SumaImporte));
        }
        else{
            JOptionPane.showMessageDialog(this, "Asigne un valor numerico al importe");
            return;
        }      
        //Agregar la informacion al Arreglo Correspondiente
        this.concepto.add(Concepto);
        this.descripcion.add(Descripcion);
        this.importe.add(Integer.parseInt(Importe));
        
        OT+=fila+1;//Orden de trabajo
        //Mostrar la informacion a la tabla en los lugares adecuados
        Object[] datos = {OT, Concepto, Descripcion, Importe };
        DefaultTableModel tabla = (DefaultTableModel) tblDatosProyecto.getModel();
        tabla.addRow(datos);
        //Limpiar los campos del formulario
        this.txtConcepto.setText("");
        this.txtDescripcionEntregable.setText("");
        this.txtImporte.setText("");
        this.txtConcepto.setFocusable(true);
    }//GEN-LAST:event_btnAgregarEntregableActionPerformed

    private void btnAgregarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActividadActionPerformed
        // TODO add your handling code here:
        //Contar las filas de la tabla
        int filas = this.tblActividades.getRowCount();
        //Obtener la informacion proporcionada desde el formulario
        String Actividad = this.txtActividad.getText();
        //Verificar que el campo no este vacio
        if(Actividad.isEmpty()){
            JOptionPane.showMessageDialog(this, "El campo de Actividad, esta vacío.");
            return;
        }
     //Guardar las actividades registradas en el arreglo
     this.Actividades.add(Actividad);
     //Mostrar la infomacion en el campo correspondiente de la tabla
     Object[] informacion = {filas+1, Actividad};
     DefaultTableModel tabla = (DefaultTableModel) tblActividades.getModel();
     tabla.addRow(informacion);
     //Limpiar el campo de actividad
     this.txtActividad.setText(""); 
     this.txtActividad.setFocusable(true);
     
    }//GEN-LAST:event_btnAgregarActividadActionPerformed

    private void jbtnAgregarGrupoTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarGrupoTrabajoActionPerformed
        // TODO add your handling code here:           
      frmEquipoTrabajo ventanaEquipoTrabajo = new frmEquipoTrabajo();
      this.Entregables.setDescripcion(this.descripcion);
      ventanaEquipoTrabajo.RecibirElementos(this.Actividades,this.Entregables.getDescripcion());
      ventanaEquipoTrabajo.setLocationRelativeTo(this);
      ventanaEquipoTrabajo.setVisible(true);
    }//GEN-LAST:event_jbtnAgregarGrupoTrabajoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregarActividad;
    private javax.swing.JToggleButton btnAgregarEntregable;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JToggleButton btnEliminarActividad;
    private javax.swing.JToggleButton btnGuardarProyecto;
    private javax.swing.JToggleButton btnQuitarEntregable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton jbtnAgregarGrupoTrabajo;
    private javax.swing.JLabel jlblActivdad;
    private javax.swing.JLabel jlblAdminProyecto;
    private javax.swing.JLabel jlblAdminProyecto1;
    private javax.swing.JLabel jlblEspecificacionEntregables;
    private javax.swing.JLabel lblConcepto;
    private javax.swing.JLabel lblCorreoAdminProyecto;
    private javax.swing.JLabel lblCorreoTecnicoProyecto;
    private javax.swing.JLabel lblDescripcionActividades;
    private javax.swing.JLabel lblDescripcionProyecto;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JLabel lblImporteEstimado;
    private javax.swing.JLabel lblJustificacionProyecto;
    private javax.swing.JLabel lblObjetivoProyecto;
    private javax.swing.JLabel lblResultadosEsperados;
    private javax.swing.JLabel lblSolicitudproyecto;
    private javax.swing.JLabel lblSumaImporte;
    private javax.swing.JLabel lblTecnicoProyecto;
    private javax.swing.JLabel lblTelefonAdminProyecto;
    private javax.swing.JLabel lblTelefonoTecnicoProyecto;
    private javax.swing.JLabel lblTituloProyecto;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JPanel pnlSolicitudProyecto;
    private javax.swing.JScrollPane scrSolicitud;
    private javax.swing.JTable tblActividades;
    private javax.swing.JTable tblDatosProyecto;
    private javax.swing.JTextArea txtActividad;
    private javax.swing.JTextPane txtConcepto;
    private javax.swing.JTextField txtCorreoAdminProyecto;
    private javax.swing.JTextField txtCorreoTecnicoProyecto;
    private javax.swing.JTextArea txtDescripcionEntregable;
    private javax.swing.JTextArea txtDescripcionProyecto;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextPane txtImporte;
    private javax.swing.JTextArea txtJustificacionProyecto;
    private javax.swing.JTextField txtNombreAdminProyecto;
    private javax.swing.JTextField txtNombreTecnicoProyecto;
    private javax.swing.JTextArea txtObjetivoProyecto;
    private javax.swing.JTextArea txtResultadosEsperados;
    private javax.swing.JTextField txtTelefonoAdminPojecto;
    private javax.swing.JTextField txtTelefonoTecniproyecto;
    private javax.swing.JTextArea txtTituloProyecto;
    // End of variables declaration//GEN-END:variables
}
