/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ElementosAdministracion;

import Clases.Entregables;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import jdk.nashorn.internal.objects.NativeArray;

/**
 *
 * @author AbrilMtz
 */
public class frmEquipoTrabajo extends javax.swing.JFrame {

    ArrayList<String> Actividades;
    ArrayList<String>  ListaEntregables;

    public frmEquipoTrabajo() {
        initComponents();
    }
    public void RecibirElementos(ArrayList<String> _actividades, ArrayList<String> _listaEntregables){
        this.Actividades = _actividades;
        this.ListaEntregables = _listaEntregables;   
        int contador1 = Actividades.size();
        int contador2 = ListaEntregables.size();        
        for (int i = 0; i<contador1; i++){
            this.jcbxActividadEspecifica.addItem(Actividades.get(i));
        }
        for (int i = 0; i<contador2; i++){
            this.jcbxEntregableEspecifico.addItem(ListaEntregables.get(i));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnGuardarEquipoTrabajo = new javax.swing.JToggleButton();
        JbtnCancelar = new javax.swing.JToggleButton();
        jlblNombreIntegrante = new javax.swing.JLabel();
        jlblTelefonoIntegrante = new javax.swing.JLabel();
        lblCorreoIntegrante = new javax.swing.JLabel();
        lblRfcIntegrante = new javax.swing.JLabel();
        jlblDuracionParticipacion = new javax.swing.JLabel();
        jlblSueldoMensual = new javax.swing.JLabel();
        jlblInformacionRelevante = new javax.swing.JLabel();
        jlblProductoQueGenera = new javax.swing.JLabel();
        jtxtnombreIntegrante = new javax.swing.JTextField();
        jtxtTelefonoIntegrante = new javax.swing.JTextField();
        jtxtCorreoIntegrante = new javax.swing.JTextField();
        jtxtRFCIntegrante = new javax.swing.JTextField();
        jtxtSueldoMensual = new javax.swing.JTextField();
        jdFechanicio = new com.toedter.calendar.JDateChooser();
        jdFechaTermino = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlblDescripción = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtDescripcion = new javax.swing.JTextArea();
        jcbxEntregableEspecifico = new javax.swing.JComboBox();
        jlblEntregableEspecifico = new javax.swing.JLabel();
        jlblActividadEspecifica = new javax.swing.JLabel();
        jcbxActividadEspecifica = new javax.swing.JComboBox();
        jbtnSeleccionarArchivo = new javax.swing.JToggleButton();
        jlblNombreArchivo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        jbtnGuardarEquipoTrabajo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbtnGuardarEquipoTrabajo.setText("Guardar");
        jbtnGuardarEquipoTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarEquipoTrabajoActionPerformed(evt);
            }
        });

        JbtnCancelar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        JbtnCancelar.setText("Cancelar");
        JbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnCancelarActionPerformed(evt);
            }
        });

        jlblNombreIntegrante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblNombreIntegrante.setText("Nombre");

        jlblTelefonoIntegrante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblTelefonoIntegrante.setText("Teléfono");

        lblCorreoIntegrante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCorreoIntegrante.setText("Correo");

        lblRfcIntegrante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRfcIntegrante.setText("RFC");

        jlblDuracionParticipacion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblDuracionParticipacion.setText("Duracion de Participacion");

        jlblSueldoMensual.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblSueldoMensual.setText("Sueldo Mensual");

        jlblInformacionRelevante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblInformacionRelevante.setText("Información Relevante");

        jlblProductoQueGenera.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblProductoQueGenera.setText("Producto que genera");

        jtxtnombreIntegrante.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtxtTelefonoIntegrante.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtxtCorreoIntegrante.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtxtRFCIntegrante.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtxtSueldoMensual.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jdFechanicio.setToolTipText("");

        jdFechaTermino.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setText("De");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setText("a");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlblDescripción.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblDescripción.setText("Descripción");

        jtxtDescripcion.setColumns(20);
        jtxtDescripcion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxtDescripcion.setRows(5);
        jScrollPane1.setViewportView(jtxtDescripcion);

        jcbxEntregableEspecifico.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jlblEntregableEspecifico.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblEntregableEspecifico.setText("Entregable específico");

        jlblActividadEspecifica.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblActividadEspecifica.setText("Actividad específica");

        jcbxActividadEspecifica.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jcbxActividadEspecifica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jlblDescripción)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblEntregableEspecifico))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblActividadEspecifica))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jcbxEntregableEspecifico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jlblEntregableEspecifico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbxEntregableEspecifico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlblActividadEspecifica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbxActividadEspecifica)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblDescripción)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jbtnSeleccionarArchivo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbtnSeleccionarArchivo.setText("Seleccionar archivo");
        jbtnSeleccionarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSeleccionarArchivoActionPerformed(evt);
            }
        });

        jlblNombreArchivo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblNombreArchivo.setText("Nombre del Archivo");
        jlblNombreArchivo.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jlblNombreArchivo.setOpaque(true);
        jlblNombreArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblNombreArchivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jbtnSeleccionarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jlblNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblInformacionRelevante)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlblTelefonoIntegrante)
                                        .addGap(234, 234, 234)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlblDuracionParticipacion)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jdFechanicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jtxtTelefonoIntegrante, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jdFechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblSueldoMensual)
                                    .addComponent(jtxtSueldoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jlblProductoQueGenera)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblNombreIntegrante)
                                .addGap(369, 369, 369)
                                .addComponent(lblRfcIntegrante)
                                .addGap(200, 200, 200))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtnombreIntegrante, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtRFCIntegrante, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCorreoIntegrante)
                                    .addComponent(jtxtCorreoIntegrante, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnGuardarEquipoTrabajo)
                .addGap(18, 18, 18)
                .addComponent(JbtnCancelar)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblNombreIntegrante)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRfcIntegrante)
                        .addComponent(lblCorreoIntegrante)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtnombreIntegrante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtRFCIntegrante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCorreoIntegrante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblTelefonoIntegrante)
                            .addComponent(jlblDuracionParticipacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtxtTelefonoIntegrante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jdFechanicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdFechaTermino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblSueldoMensual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtSueldoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addComponent(jlblInformacionRelevante)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSeleccionarArchivo)
                    .addComponent(jlblNombreArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblProductoQueGenera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnGuardarEquipoTrabajo)
                    .addComponent(JbtnCancelar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSeleccionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSeleccionarArchivoActionPerformed
        // TODO add your handling code here:
        String Archivo, Ruta;        
        //Opcion para escoger un archivo
        JFileChooser fc=new JFileChooser();    
        //Creamos un filtro para que solo se puedan seleccionar archivos PDF
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.PDF", "pdf");
        //Le indicamos el filtro al filechooser
        fc.setFileFilter(filtro);
        //Abrimos la ventana, guardamos la opcion seleccionada por el usuario
        int seleccion=fc.showOpenDialog(fc);        
        File abre=fc.getSelectedFile();        
        //Si el usuario, Hace Click en aceptar        
        if(seleccion==JFileChooser.APPROVE_OPTION){
            //Seleccionamos el fichero
            File fichero=fc.getSelectedFile();
            //Ecribe la ruta del fichero seleccionado en el campo de texto
            Archivo = fichero.getName();
            this.jlblNombreArchivo.setText(Archivo);
            Ruta = fichero.getAbsolutePath();
            this.jbtnSeleccionarArchivo.setSelected(false);
        }
        else if(abre == null){
            JOptionPane.showMessageDialog(this,"" +"\nNo se ha Seleccionado un archivo","Aviso!!!",JOptionPane.WARNING_MESSAGE);
            this.jlblNombreArchivo.setText("Nombre del Archivo");
       }       
    }//GEN-LAST:event_jbtnSeleccionarArchivoActionPerformed

    private void jlblNombreArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblNombreArchivoMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Mostrar PDF");
    }//GEN-LAST:event_jlblNombreArchivoMouseClicked

    private void jbtnGuardarEquipoTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarEquipoTrabajoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Los datos se han guardado correctamente");
    }//GEN-LAST:event_jbtnGuardarEquipoTrabajoActionPerformed

    private void JbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JbtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEquipoTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEquipoTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEquipoTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEquipoTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEquipoTrabajo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton JbtnCancelar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jbtnGuardarEquipoTrabajo;
    private javax.swing.JToggleButton jbtnSeleccionarArchivo;
    private javax.swing.JComboBox jcbxActividadEspecifica;
    private javax.swing.JComboBox jcbxEntregableEspecifico;
    private com.toedter.calendar.JDateChooser jdFechaTermino;
    private com.toedter.calendar.JDateChooser jdFechanicio;
    private javax.swing.JLabel jlblActividadEspecifica;
    private javax.swing.JLabel jlblDescripción;
    private javax.swing.JLabel jlblDuracionParticipacion;
    private javax.swing.JLabel jlblEntregableEspecifico;
    private javax.swing.JLabel jlblInformacionRelevante;
    private javax.swing.JLabel jlblNombreArchivo;
    private javax.swing.JLabel jlblNombreIntegrante;
    private javax.swing.JLabel jlblProductoQueGenera;
    private javax.swing.JLabel jlblSueldoMensual;
    private javax.swing.JLabel jlblTelefonoIntegrante;
    private javax.swing.JTextField jtxtCorreoIntegrante;
    private javax.swing.JTextArea jtxtDescripcion;
    private javax.swing.JTextField jtxtRFCIntegrante;
    private javax.swing.JTextField jtxtSueldoMensual;
    private javax.swing.JTextField jtxtTelefonoIntegrante;
    private javax.swing.JTextField jtxtnombreIntegrante;
    private javax.swing.JLabel lblCorreoIntegrante;
    private javax.swing.JLabel lblRfcIntegrante;
    // End of variables declaration//GEN-END:variables
}
