/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ElementosGestionComercial;


import Clases.Cliente;
import AdminAplication.MetodosPrincipales;
import AdminAplication.ProcesosMongoDB;
import javax.swing.JOptionPane;

/**
 *
 * @author AbrilMtz
 */
public class RegistroClientes extends javax.swing.JPanel {
    
    MetodosPrincipales Operaciones = new MetodosPrincipales();
    ProcesosMongoDB ProcedimientoMongo = new ProcesosMongoDB();
    
    String fecha; 
    /**
     * Creates new form boton_2
     */
    public RegistroClientes() {
        initComponents();
        
        fecha = Operaciones.ObtenerFechaHora();
        lblFechaRegistro.setText("Fecha de Registro: \n" + fecha);   
        //ProcedimientoMongo.Mostrar("SI1701");
    }
    
    private void LimpiarForm(){
        txtCorreoRepLegal.setText("");
        txtDescripcionEmpresa.setText("");
        txtpDireccion.setText("");
        txtExtencionEmpresa.setText("");
        txtExtencionRepLegal.setText("");
        txtNombreComercial.setText("");
        txtNombreRepLegal.setText("");
        txtRENIECYT.setText("");
        txtRFC.setText("");
        txtRazonS.setText("");
        txtTelefono2RepLegal.setText("");
        txtTelefonoEmpresa.setText("");
        txtTelefonoRepLegal.setText("");                     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrPanelGestion = new javax.swing.JScrollPane();
        jpanelGestion = new javax.swing.JPanel();
        jlblRENIECYT = new javax.swing.JLabel();
        jlblVigenciaRENIECYT = new javax.swing.JLabel();
        jlblDescripcionEmpresa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlblRepEmpresa = new javax.swing.JLabel();
        jlblTelefonoRepLegal = new javax.swing.JLabel();
        jlblCorreoRepLegal = new javax.swing.JLabel();
        jlblExtensiónRepLegal = new javax.swing.JLabel();
        jlblOtroTel = new javax.swing.JLabel();
        txtNombreRepLegal = new javax.swing.JTextField();
        txtTelefonoRepLegal = new javax.swing.JTextField();
        txtExtencionRepLegal = new javax.swing.JTextField();
        txtTelefono2RepLegal = new javax.swing.JTextField();
        txtCorreoRepLegal = new javax.swing.JTextField();
        txtRENIECYT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcionEmpresa = new javax.swing.JTextArea();
        jbtnCancelar = new javax.swing.JToggleButton();
        jbtnGuardar = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jdtVigenciaRENIECYT = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlblRazonSocial = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRazonS = new javax.swing.JTextField();
        jlblNombreComercial = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreComercial = new javax.swing.JTextField();
        jlblDireccion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JScroollPaneDireccion = new javax.swing.JScrollPane();
        txtpDireccion = new javax.swing.JTextPane();
        jlblFechaRegistro = new javax.swing.JLabel();
        lblFechaRegistro = new javax.swing.JLabel();
        jlblRFC = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        jlblTelefonoempresa = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTelefonoEmpresa = new javax.swing.JTextField();
        txtExtencionEmpresa = new javax.swing.JTextField();
        jlblExtencionEmpresa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(1200, 570));

        scrPanelGestion.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrPanelGestion.setPreferredSize(new java.awt.Dimension(1180, 540));

        jpanelGestion.setForeground(new java.awt.Color(255, 51, 51));
        jpanelGestion.setAutoscrolls(true);
        jpanelGestion.setPreferredSize(new java.awt.Dimension(1180, 860));
        jpanelGestion.setRequestFocusEnabled(false);

        jlblRENIECYT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblRENIECYT.setText("RENIECYT");

        jlblVigenciaRENIECYT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblVigenciaRENIECYT.setText("Vigencia de RENIECYT");

        jlblDescripcionEmpresa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblDescripcionEmpresa.setText("Descripción de la empresa o Información Adicional");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Informacion del Representante Legal");

        jlblRepEmpresa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblRepEmpresa.setText("Nombre");

        jlblTelefonoRepLegal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblTelefonoRepLegal.setText("Teléfono");

        jlblCorreoRepLegal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblCorreoRepLegal.setText("Correo");

        jlblExtensiónRepLegal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblExtensiónRepLegal.setText("Extención");

        jlblOtroTel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblOtroTel.setText("Otro Teléfono");

        txtNombreRepLegal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNombreRepLegal.setPreferredSize(new java.awt.Dimension(630, 25));

        txtTelefonoRepLegal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtExtencionRepLegal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtTelefono2RepLegal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtCorreoRepLegal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtRENIECYT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtDescripcionEmpresa.setColumns(20);
        txtDescripcionEmpresa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDescripcionEmpresa.setRows(5);
        jScrollPane1.setViewportView(txtDescripcionEmpresa);

        jbtnCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jbtnGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbtnGuardar.setText("Guardar");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("*");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("*");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("*");

        jdtVigenciaRENIECYT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel10.setText("Registro de Clientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlblRazonSocial.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblRazonSocial.setText("Razón Social");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("*");

        txtRazonS.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jlblNombreComercial.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblNombreComercial.setText("Nombre Comercial");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("*");

        txtNombreComercial.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jlblDireccion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblDireccion.setText("Dirección");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("*");

        txtpDireccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        JScroollPaneDireccion.setViewportView(txtpDireccion);

        jlblFechaRegistro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblFechaRegistro.setText("Fecha de Registro");

        lblFechaRegistro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblFechaRegistro.setText("Fecha de Registro: ");

        jlblRFC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblRFC.setText("RFC");

        txtRFC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jlblTelefonoempresa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblTelefonoempresa.setText("Telefono de empresa");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("*");

        txtTelefonoEmpresa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtExtencionEmpresa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jlblExtencionEmpresa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblExtencionEmpresa.setText("Extensión");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JScroollPaneDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblDireccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblNombreComercial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombreComercial, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblRazonSocial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtRazonS, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 94, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtRFC)
                        .addComponent(lblFechaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblRFC)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jlblTelefonoempresa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtTelefonoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(35, 35, 35)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlblExtencionEmpresa)
                                .addComponent(txtExtencionEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jlblFechaRegistro))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblRazonSocial)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlblFechaRegistro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRazonS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblFechaRegistro)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblNombreComercial)
                            .addComponent(jLabel4))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblRFC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JScroollPaneDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblExtencionEmpresa)
                            .addComponent(jlblTelefonoempresa)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtExtencionEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefonoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Información de la Empresa");

        javax.swing.GroupLayout jpanelGestionLayout = new javax.swing.GroupLayout(jpanelGestion);
        jpanelGestion.setLayout(jpanelGestionLayout);
        jpanelGestionLayout.setHorizontalGroup(
            jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelGestionLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanelGestionLayout.createSequentialGroup()
                        .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jlblDescripcionEmpresa))
                        .addGap(0, 779, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanelGestionLayout.createSequentialGroup()
                        .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpanelGestionLayout.createSequentialGroup()
                                .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jpanelGestionLayout.createSequentialGroup()
                                        .addComponent(jbtnGuardar)
                                        .addGap(110, 110, 110)
                                        .addComponent(jbtnCancelar))
                                    .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jpanelGestionLayout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtNombreRepLegal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(jpanelGestionLayout.createSequentialGroup()
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jlblRepEmpresa)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jpanelGestionLayout.createSequentialGroup()
                                                        .addComponent(jlblCorreoRepLegal)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(txtCorreoRepLegal, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jlblRENIECYT)
                                                .addComponent(txtRENIECYT, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jpanelGestionLayout.createSequentialGroup()
                                                        .addComponent(jlblTelefonoRepLegal)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(109, 109, 109)
                                                        .addComponent(jlblExtensiónRepLegal))
                                                    .addGroup(jpanelGestionLayout.createSequentialGroup()
                                                        .addComponent(txtTelefonoRepLegal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(35, 35, 35)
                                                        .addComponent(txtExtencionRepLegal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jpanelGestionLayout.createSequentialGroup()
                                                        .addComponent(jlblOtroTel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtTelefono2RepLegal, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(jlblVigenciaRENIECYT, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jdtVigenciaRENIECYT, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jpanelGestionLayout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(29, 29, 29)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpanelGestionLayout.setVerticalGroup(
            jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelGestionLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanelGestionLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblRepEmpresa)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(txtNombreRepLegal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelGestionLayout.createSequentialGroup()
                        .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTelefonoRepLegal)
                            .addGroup(jpanelGestionLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlblExtensiónRepLegal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefonoRepLegal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExtencionRepLegal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelGestionLayout.createSequentialGroup()
                        .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblCorreoRepLegal)
                            .addComponent(jLabel9))
                        .addGap(4, 4, 4)
                        .addComponent(txtCorreoRepLegal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelGestionLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono2RepLegal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblOtroTel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblRENIECYT)
                    .addComponent(jlblVigenciaRENIECYT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRENIECYT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdtVigenciaRENIECYT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlblDescripcionEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jpanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnGuardar)
                    .addComponent(jbtnCancelar))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        scrPanelGestion.setViewportView(jpanelGestion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrPanelGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrPanelGestion, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        String Resultado;
        //Revisar que los campos obligatorios no estén vacios
        if (txtRazonS.getText().isEmpty() || txtNombreComercial.getText().isEmpty() || txtpDireccion.getText().isEmpty()
            || txtTelefonoEmpresa.getText().isEmpty() || txtNombreRepLegal.getText().isEmpty() || txtTelefonoRepLegal.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this,"Alguno de los campos obligatorios está vacío");
            return;
        }
        //Validar RFC primeramente si tiene escrito algun valor y despues revisar que tenga el formato correcto
        if(txtRFC.getText().length() != 0 && Operaciones.ValidarRFC(txtRFC.getText()) == (false) ){
            JOptionPane.showMessageDialog(this,"El RFC proporcionado es Incorrecto");
            return;
        }
        //creacion de un Objeto Cliente con los datos proporcionados en el Form
        Cliente cliente = new Cliente();
        cliente.setRazonSocial(txtRazonS.getText());
        cliente.setFechaRegistro(fecha);
        cliente.setNombreComercial(txtNombreComercial.getText());
        cliente.setRFC(txtRFC.getText());
        cliente.setDireccion(txtpDireccion.getText());
        cliente.setTelefonEmpresa(txtTelefonoEmpresa.getText());
        cliente.setExtensionEmpresa(txtExtencionEmpresa.getText());
        cliente.setNombreRepresentante(txtNombreRepLegal.getText());
        cliente.setTelefonoRepresentante(txtTelefonoRepLegal.getText());
        cliente.setExtensionTelRepresentante(txtExtencionRepLegal.getText());
        cliente.setCorreoRepresentante(txtCorreoRepLegal.getText());
        cliente.setTelefono2Representante(txtTelefono2RepLegal.getText());
        cliente.setRENIECYT(txtRENIECYT.getText());
        cliente.setVigenciaRENIECYT(jdtVigenciaRENIECYT.getDate().toString());
        cliente.setDescripcion(txtDescripcionEmpresa.getText());
        //Guardar la informacion con el método GuardarCliente
        Resultado = ProcedimientoMongo.GuardarCliente("Clientes", cliente);

        if (Resultado.equals("Guardado"))
        {
            JOptionPane.showMessageDialog(this, "Los datos han sido Guardados correctamente");
            this.LimpiarForm();
        }
    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        // TODO add your handling code here:
        this.LimpiarForm();
    }//GEN-LAST:event_jbtnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScroollPaneDireccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jbtnCancelar;
    private javax.swing.JToggleButton jbtnGuardar;
    private com.toedter.calendar.JDateChooser jdtVigenciaRENIECYT;
    private javax.swing.JLabel jlblCorreoRepLegal;
    private javax.swing.JLabel jlblDescripcionEmpresa;
    private javax.swing.JLabel jlblDireccion;
    private javax.swing.JLabel jlblExtencionEmpresa;
    private javax.swing.JLabel jlblExtensiónRepLegal;
    private javax.swing.JLabel jlblFechaRegistro;
    private javax.swing.JLabel jlblNombreComercial;
    private javax.swing.JLabel jlblOtroTel;
    private javax.swing.JLabel jlblRENIECYT;
    private javax.swing.JLabel jlblRFC;
    private javax.swing.JLabel jlblRazonSocial;
    private javax.swing.JLabel jlblRepEmpresa;
    private javax.swing.JLabel jlblTelefonoRepLegal;
    private javax.swing.JLabel jlblTelefonoempresa;
    private javax.swing.JLabel jlblVigenciaRENIECYT;
    private javax.swing.JPanel jpanelGestion;
    private javax.swing.JLabel lblFechaRegistro;
    private javax.swing.JScrollPane scrPanelGestion;
    private javax.swing.JTextField txtCorreoRepLegal;
    private javax.swing.JTextArea txtDescripcionEmpresa;
    private javax.swing.JTextField txtExtencionEmpresa;
    private javax.swing.JTextField txtExtencionRepLegal;
    private javax.swing.JTextField txtNombreComercial;
    private javax.swing.JTextField txtNombreRepLegal;
    private javax.swing.JTextField txtRENIECYT;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtRazonS;
    private javax.swing.JTextField txtTelefono2RepLegal;
    private javax.swing.JTextField txtTelefonoEmpresa;
    private javax.swing.JTextField txtTelefonoRepLegal;
    private javax.swing.JTextPane txtpDireccion;
    // End of variables declaration//GEN-END:variables

}