package AdminAplication;
	
import ElementosAdministracion.AltaActividades;
import java.awt.*;	
import ElementosGestionComercial.RegistroClientes;
import ElementosAdministracion.AltaSolicitudProyecto;

public class jfrmMain extends javax.swing.JFrame {
    /**
     * Creates new form jfrmPrincipal
     */
    
    private final MetodosPrincipales Operaciones = new MetodosPrincipales();
    
    public jfrmMain() {
        initComponents();
        
        //OBTENER LA FECHA Y HORA DE INGRESO
        String hora= Operaciones.ObtenerFechaHora();
        jlblTextoHora.setText("Fecha y Hora de Entrada: "+hora);
             
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlBody = new javax.swing.JPanel();
        jlblTextoHora = new javax.swing.JLabel();
        jmbAccionesPrincipales = new javax.swing.JMenuBar();
        jmDireccion = new javax.swing.JMenu();
        jmGestionComercial = new javax.swing.JMenu();
        jmAltaCliente = new javax.swing.JMenu();
        jmGestionProyectos = new javax.swing.JMenu();
        jmGestioProyectos = new javax.swing.JMenu();
        jmAdministracionProyecto = new javax.swing.JMenu();
        jmAltaProyecto = new javax.swing.JMenu();
        jmAltaActividades = new javax.swing.JMenu();
        jmSeguimientoProyecto = new javax.swing.JMenu();
        jmCierreProyecto = new javax.swing.JMenu();
        jmDiseñoInnovacion = new javax.swing.JMenu();
        jmAdministracionRH = new javax.swing.JMenu();
        jmAdministracionPuestos = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jmAdministracionPersonal = new javax.swing.JMenu();
        jmAltaPersonal = new javax.swing.JMenu();
        jmBajaPersonal = new javax.swing.JMenu();
        jmGestionRMateriales = new javax.swing.JMenu();
        jmGestionRFinancieros = new javax.swing.JMenu();
        jmAdministracionProduccion = new javax.swing.JMenu();
        jmAvisos = new javax.swing.JMenu();
        jmAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jpnlBody.setAutoscrolls(true);
        jpnlBody.setPreferredSize(new java.awt.Dimension(1250, 550));

        javax.swing.GroupLayout jpnlBodyLayout = new javax.swing.GroupLayout(jpnlBody);
        jpnlBody.setLayout(jpnlBodyLayout);
        jpnlBodyLayout.setHorizontalGroup(
            jpnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        jpnlBodyLayout.setVerticalGroup(
            jpnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        jlblTextoHora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblTextoHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("AdminAplication/Bundle"); // NOI18N
        jlblTextoHora.setText(bundle.getString("jfrmMain.jlblTextoHora.text")); // NOI18N

        jmbAccionesPrincipales.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jmbAccionesPrincipales.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jmbAccionesPrincipales.setPreferredSize(new java.awt.Dimension(1097, 30));

        jmDireccion.setText(bundle.getString("jfrmMain.jmDireccion.text")); // NOI18N
        jmbAccionesPrincipales.add(jmDireccion);

        jmGestionComercial.setText(bundle.getString("jfrmMain.jmGestionComercial.text")); // NOI18N

        jmAltaCliente.setText(bundle.getString("jfrmMain.jmAltaCliente.text")); // NOI18N
        jmAltaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAltaClienteMouseClicked(evt);
            }
        });
        jmGestionComercial.add(jmAltaCliente);

        jmbAccionesPrincipales.add(jmGestionComercial);

        jmGestionProyectos.setText(bundle.getString("jfrmMain.jmGestionProyectos.text")); // NOI18N

        jmGestioProyectos.setText(bundle.getString("jfrmMain.jmGestioProyectos.text")); // NOI18N
        jmGestioProyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmGestioProyectosMouseClicked(evt);
            }
        });
        jmGestionProyectos.add(jmGestioProyectos);

        jmAdministracionProyecto.setText(bundle.getString("jfrmMain.jmAdministracionProyecto.text")); // NOI18N

        jmAltaProyecto.setText(bundle.getString("jfrmMain.jmAltaProyecto.text")); // NOI18N
        jmAdministracionProyecto.add(jmAltaProyecto);

        jmAltaActividades.setText(bundle.getString("jfrmMain.jmAltaActividades.text")); // NOI18N
        jmAltaActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAltaActividadesMouseClicked(evt);
            }
        });
        jmAltaActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAltaActividadesActionPerformed(evt);
            }
        });
        jmAdministracionProyecto.add(jmAltaActividades);

        jmSeguimientoProyecto.setText(bundle.getString("jfrmMain.jmSeguimientoProyecto.text")); // NOI18N
        jmAdministracionProyecto.add(jmSeguimientoProyecto);

        jmCierreProyecto.setText(bundle.getString("jfrmMain.jmCierreProyecto.text")); // NOI18N
        jmAdministracionProyecto.add(jmCierreProyecto);

        jmGestionProyectos.add(jmAdministracionProyecto);

        jmDiseñoInnovacion.setText(bundle.getString("jfrmMain.jmDiseñoInnovacion.text")); // NOI18N
        jmGestionProyectos.add(jmDiseñoInnovacion);

        jmbAccionesPrincipales.add(jmGestionProyectos);

        jmAdministracionRH.setText(bundle.getString("jfrmMain.jmAdministracionRH.text")); // NOI18N

        jmAdministracionPuestos.setText(bundle.getString("jfrmMain.jmAdministracionPuestos.text")); // NOI18N

        jMenu10.setText(bundle.getString("jfrmMain.jMenu10.text")); // NOI18N
        jmAdministracionPuestos.add(jMenu10);

        jMenu11.setText(bundle.getString("jfrmMain.jMenu11.text")); // NOI18N
        jmAdministracionPuestos.add(jMenu11);

        jmAdministracionRH.add(jmAdministracionPuestos);

        jmAdministracionPersonal.setText(bundle.getString("jfrmMain.jmAdministracionPersonal.text")); // NOI18N

        jmAltaPersonal.setText(bundle.getString("jfrmMain.jmAltaPersonal.text")); // NOI18N
        jmAdministracionPersonal.add(jmAltaPersonal);

        jmBajaPersonal.setText(bundle.getString("jfrmMain.jmBajaPersonal.text")); // NOI18N
        jmAdministracionPersonal.add(jmBajaPersonal);

        jmAdministracionRH.add(jmAdministracionPersonal);

        jmbAccionesPrincipales.add(jmAdministracionRH);

        jmGestionRMateriales.setText(bundle.getString("jfrmMain.jmGestionRMateriales.text")); // NOI18N
        jmbAccionesPrincipales.add(jmGestionRMateriales);

        jmGestionRFinancieros.setText(bundle.getString("jfrmMain.jmGestionRFinancieros.text")); // NOI18N
        jmbAccionesPrincipales.add(jmGestionRFinancieros);

        jmAdministracionProduccion.setText(bundle.getString("jfrmMain.jmAdministracionProduccion.text")); // NOI18N
        jmbAccionesPrincipales.add(jmAdministracionProduccion);

        jmAvisos.setText(bundle.getString("jfrmMain.jmAvisos.text")); // NOI18N
        jmbAccionesPrincipales.add(jmAvisos);

        jmAyuda.setText(bundle.getString("jfrmMain.jmAyuda.text")); // NOI18N
        jmbAccionesPrincipales.add(jmAyuda);

        setJMenuBar(jmbAccionesPrincipales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblTextoHora)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jpnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblTextoHora)
                .addGap(7, 7, 7))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        //cerrar la aplicacion despues de tiempo iactiva
        
    }//GEN-LAST:event_formMouseMoved

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:        
        String horaSalida = Operaciones.ObtenerFechaHora();
        System.out.println("Fecha y Hora de Salida: " + horaSalida);
        System.exit(0);
               
    }//GEN-LAST:event_formWindowClosing

    private void jmAltaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAltaClienteMouseClicked
        // TODO add your handling code here:
        RegistroClientes panelActivo = new RegistroClientes();
        panelActivo.setSize(jpnlBody.getWidth(),jpnlBody.getHeight());
        panelActivo.setLocation(5, 5);
        jpnlBody.removeAll();
        jpnlBody.add(panelActivo, BorderLayout.CENTER);
        jpnlBody.revalidate();
        jpnlBody.repaint();
    }//GEN-LAST:event_jmAltaClienteMouseClicked

    private void jmGestioProyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmGestioProyectosMouseClicked
        // TODO add your handling code here:
        AltaSolicitudProyecto panelActivo = new AltaSolicitudProyecto();
        panelActivo.setSize(jpnlBody.getWidth(),jpnlBody.getHeight());
        panelActivo.setLocation(5, 5);
        jpnlBody.removeAll();
        jpnlBody.add(panelActivo, BorderLayout.CENTER);
        jpnlBody.revalidate();
        jpnlBody.repaint();
    }//GEN-LAST:event_jmGestioProyectosMouseClicked

    private void jmAltaActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAltaActividadesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jmAltaActividadesActionPerformed

    private void jmAltaActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAltaActividadesMouseClicked
        // TODO add your handling code here:       
        AltaActividades panelActivo = new AltaActividades();
        panelActivo.setSize(jpnlBody.getWidth(),jpnlBody.getHeight());
        panelActivo.setLocation(5, 5);
        jpnlBody.removeAll();
        jpnlBody.add(panelActivo, BorderLayout.CENTER);
        jpnlBody.revalidate();
        jpnlBody.repaint();
    }//GEN-LAST:event_jmAltaActividadesMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new jfrmMain().setVisible(true);
        });
    }
// <editor-fold>
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JLabel jlblTextoHora;
    private javax.swing.JMenu jmAdministracionPersonal;
    private javax.swing.JMenu jmAdministracionProduccion;
    private javax.swing.JMenu jmAdministracionProyecto;
    private javax.swing.JMenu jmAdministracionPuestos;
    private javax.swing.JMenu jmAdministracionRH;
    private javax.swing.JMenu jmAltaActividades;
    private javax.swing.JMenu jmAltaCliente;
    private javax.swing.JMenu jmAltaPersonal;
    private javax.swing.JMenu jmAltaProyecto;
    private javax.swing.JMenu jmAvisos;
    private javax.swing.JMenu jmAyuda;
    private javax.swing.JMenu jmBajaPersonal;
    private javax.swing.JMenu jmCierreProyecto;
    private javax.swing.JMenu jmDireccion;
    private javax.swing.JMenu jmDiseñoInnovacion;
    private javax.swing.JMenu jmGestioProyectos;
    private javax.swing.JMenu jmGestionComercial;
    private javax.swing.JMenu jmGestionProyectos;
    private javax.swing.JMenu jmGestionRFinancieros;
    private javax.swing.JMenu jmGestionRMateriales;
    private javax.swing.JMenu jmSeguimientoProyecto;
    private javax.swing.JMenuBar jmbAccionesPrincipales;
    public javax.swing.JPanel jpnlBody;
    // End of variables declaration//GEN-END:variables
// </editor-fold> 
}
